name: MacOS-CI

on:
  push:
    tags: 
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - qt_version: 6.5.2
            package_name: gdownloader_macos

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          fetch-tags: true
          submodules: recursive

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          modules: 'qt5compat qtwebsockets qt3d qtshadertools'

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Setup vcpkg
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: arm64-osx-release
          token: ${{ github.token }}
          github-binarycache: true

      - name: Build
        run: |
          echo "vcpkg-cmake-config: ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}"
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B build -S ${{ github.workspace }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/macos_package -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --parallel
          cmake --install build --config Release
      - name: echo package name
        run: |
          echo "ls macos_package"
          ls macos_package

      - name: Upload Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file_glob: true
          file: macos_package/*
          overwrite: true
