name: MacOS-CI

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - qt_version: 6.5.2
            package_name: gdownloader_macos

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          fetch-tags: true
          submodules: recursive

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          modules: 'qt5compat qtwebsockets qt3d qtshadertools'

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Setup vcpkg
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: arm64-osx-release
          token: ${{ github.token }}
          github-binarycache: true

      - name: Build
        run: |
          echo "vcpkg-cmake-config: ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}"
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B build -S ${{ github.workspace }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/macos_package -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --parallel
          cmake --install build --config Release

      - name: Package Debug Symbols
        run: |
          mkdir macos_debug_symbols
          find build -name "*.dSYM" -exec cp -r {} macos_debug_symbols/ \;
          zip -r macos_package/${{ matrix.package_name }}-${{ matrix.qt_version }}-debug-symbols.zip macos_debug_symbols

      - name: Upload Debug Symbols
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-Debug-Symbols
          path: macos_package/${{ matrix.package_name }}-${{ matrix.qt_version }}-debug-symbols.zip

      - name: Upload DMG
        #if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-DMG
          path: macos_package/*.dmg
          
      - name: echo package name
        run: |
          echo "ls macos_package"
          ls macos_package

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file_glob: true
          file: macos_package/*
          overwrite: true
          tag: ${{ steps.get_version.outputs.version }}
