name: Windows-CI

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - qt_version: 6.5.2
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            package_name: gdownloader_windows
    steps:
      - name: checkout-branch
        uses: actions/checkout@v4

        with:
          fetch-depth: 0 
          fetch-tags: true
          submodules: recursive

      - name: setup-QT  
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qt_arch }}
          modules: 'qt5compat qtwebsockets qt3d qtshadertools'
          
      - name: vcpkg build
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true
          
      - name: Build
        id: msvc_build
        shell: cmd
        run: |
          echo "vcpkg-cmake-config: ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}"
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B build -S ${{ github.workspace }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/windows_package -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_CXX_FLAGS="-D_WIN32_WINNT=0x0A00"
          cmake --build build --config Release --parallel
          mkdir windows_pdb
          copy /Y build\Release\bin\*.pdb windows_pdb
          del /S /Q build\Release\bin\*.pdb
          del /S /Q build\Release\bin\*.lib
          del /S /Q build\Release\bin\*.exp
          cmake --install build --config Release 
    
      - name: package
        id: package
        shell: pwsh
        run: |
           Compress-Archive -Path windows_pdb -DestinationPath ${{ matrix.package_name }}-${{ matrix.qt_version }}-${{ matrix.msvc_arch }}.zip -Force
           echo "::set-output name=package_name::${{ matrix.package_name }}-${{ matrix.qt_version }}-${{ matrix.msvc_arch }}.zip"

      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.2
        with:
          nsis-version: '3.10'

      - name: Build Installer
        shell: cmd
        run: |
          dir build/release
          dir build/release/bin
          makensis -V4 "${{github.workspace}}/build/release/windows_installer.nsi"
          echo ${{ github.workspace }}/build/release/

      - name: Upload Installer
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: build/release/*.exe

      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file_glob: true
          file: build/release/GDownloader_windows_*.exe
          overwrite: true





          
          
