name: Windows-CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - qt_version: 6.5.2
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
    steps:
      - name: checkout-branch
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.10.0

      - name: setup-QT  
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qt_arch }}
          modules: 'qt5compat qtwebsockets'
          
      - name: vcpkg build
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true
          
      - name: Build
        id: msvc_build
        shell: cmd
        run: |
          echo "vcpkg-cmake-config: ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}"
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B build -S ${{ github.workspace }}  -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build build --config Release
      - name: package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.qt_version }}-${{ matrix.msvc_arch }}-release
          path: build/release
          
          
